/** \file diffusion_greedy.c
  * \brief Starting at the given IC, successively iterate the IM and SM to gain action.
  *
  * We use a greedy strategy to produce the diffusion pseudo-orbit: Iterate the
  * SM if it gains action, otherwise iterate the IM.
  *
  *	\remark Fourier-Polynomial coeffs for the generating function are read from
  *	files ipA.res and ipB.res, which were generated by program FP.
  *
  *	\remark Polynomial coeffs for omega are read from ipOmega.res, which was
  *	generated by P.
  *
  * \attention Caller must specify which SM to use (SM1 or SM2) as a
  * command-line argument.
  *
  * USAGE:	./diffusion_greedy SM scaledI phi, for example 
  *    ./diffusion_greedy 1 3 0
  *
  * CALLED BY:	diffusion_greedy.sh
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>       // fabs
#include "FP_module.h"
#include "P_module.h"
#include "SM_module.h"
#include "IM_module.h"

static const char ipOmega_FILE[] = "ipOmega.res";
static const char ipOmega_FILE_SM2[] = "ipOmega_SM2.res";

int
main (int argc, char *argv[])
{
	const int nfour=65; 	/* Number of Fourier coeffs used in FFT */
	const int ntori=8;		/* Number of tori used in numerical SM */

    const int N = 8;    /* Degree of Fourier series */
    const int L = 4;    /* Degree of Taylor series */

    double ipA[N+1][L+1];   /* polyn interp of Fourier coeffs A_n(I) */
    double ipB[N+1][L+1];   /* polyn interp of Fourier coeffs B_n(I) */
    double ipOmega[L+1]; 	/* polyn interp of omega(I) */

    SM_t bSM;           /* Which SM (SM1 or SM2) */
    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the SM */

    /* auxiliary vars */
    int iSM;
    int iErr;
	double phi_old;

    if(argc != 4)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s SM scaled_I phi\n",
              argv[0]);
        exit(EXIT_FAILURE);
    }

    iSM = atoi(argv[1]);
    if(iSM==1)
        bSM = SM1;
    else
        bSM = SM2;

    I = atof(argv[2]);	    /* scaled action level, e.g. I=2 */
    phi = atof(argv[3]);	/* \phi */

    /* Read FP series (polyn interp) from file */
    read_FP(N,L,bSM,ipA,ipB);

    /* Read Polynomial series from file */
	if(bSM==SM1)	read_P(L,ipOmega_FILE,ipOmega);
	else			read_P(L,ipOmega_FILE_SM2,ipOmega);

	printf("%f %f %s\n", I, phi, "IM");
    while(I<7)
    {
		/* Compute the SM: (I, phi) -> (Ip, phip) */
    iErr=SM(N, L, ipA, ipB, ipOmega, I, phi, &Ip, &phip);
    if(iErr)
    {
        fprintf(stderr, 
        "SM: Error computing the SM at I=%f, phi=%f\n", I, phi);
        exit(EXIT_FAILURE);
    }

		if(Ip>I)	/* Accept SM iterate */
		{
			I = Ip;
			phi = (phip>M_PI ? phip-M_PI : phip);
			
			printf("%f %f %s\n", I, phi, "SM");
		}
		else		/* Reject SM iterate. Take IM iterate instead. */
		{
			/* Compute the IM: (I, phi) -> (Ip, phip) */
			IM(I, phi, &Ip, &phip);
			I = Ip;
			phi_old = phi;
			phi = (phip>M_PI ? phip-M_PI : phip);

			/* If angle phi wrapped around \pi, print newline. 
			   This is a trick for correctly plotting line segments in
			   diffusion_SM2.plt.
			 */
			if(bSM==SM2 && phi_old<M_PI/2 && phi>M_PI/2) printf("\n");
				
			printf("%f %f %s\n", I, phi, "IM");
		}
    }
    return 0;
}
