/** \file diffusion_shortest_path.c
  * \brief Starting at the given IC, successively iterate the IM and SM1,SM2 to gain action.
  *
  * We use a shortest path algorithm to produce the diffusion pseudo-orbit:
  * The domain [0,2\pi] x [0,7] is subdivided in nCellsPhi x nCellsI `cells'
  * (rectangles).
  * Iterate the map (IM, SM1, SM2) dictated by the shortest path from the
  * current cell to the target cell, as found by Dijkstra's algorithm.
  *
  *	\remark Fourier-Polynomial coeffs for the generating function are read from
  *	files ipA.res and ipB.res, which were generated by program FP.
  *
  *	\remark Polynomial coeffs for omega are read from ipOmega.res, which was
  *	generated by P.
  *
  * USAGE:	./diffusion_shortest_path I_src phi_src I_target, phi_target, for example 
  *			./diffusion_shortest_path 1 3.14 7 0
  *
  * CALLED BY: diffusion_shortest_path.sh
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>       // fabs
#include <assert.h>
#include "FP_module.h"
#include "P_module.h"
#include "SM_module.h"
#include "IM_module.h"
#include "dijkstra_module.h"

static const char ipOmega_FILE[] = "ipOmega.res";
static const char ipOmega_FILE_SM2[] = "ipOmega_SM2.res";

const int nfour=65; 	/* Number of Fourier coeffs used in FFT */
const int ntori=8;		/* Number of tori used in numerical SM */

const int N = 8;    /* Degree of Fourier series */
const int L = 4;    /* Degree of Taylor series */

const int nCellsI = 30;		/* Number of cells in the I direction */
const int nCellsPhi = 30;	/* Number of cells in the phi direction */
const int nCells = nCellsI*nCellsPhi;	/* Total number of cells (vertices) */

const double dI = 7.0/nCellsI;
const double dphi = 2*M_PI/nCellsPhi;

void cell2pt(int i, int j, double *I, double *phi)
{
	assert(i>= 0 && i<nCellsI);
	assert(j>= 0 && j<nCellsPhi);

	*I = i*dI + dI/2;
	*phi = j*dphi + dphi/2;
}

void pt2cell(double I, double phi, int *i, int *j)
{
	assert(I>= 0);
	assert(phi>= 0 && phi<=2*M_PI);

	if(I<7) 
	{
		*i = (int) (I/dI);
	}
	else
	{
		/* Cell is outside domain. Identify it with closest cell */
		*i = nCellsI-1;
	}
	*j = (int) (phi/dphi);
}

void initGraph(double ipA[N+1][L+1], double ipB[N+1][L+1],
		double ipOmega[L+1],
		double ipA_SM2[N+1][L+1], double ipB_SM2[N+1][L+1],
        double ipOmega_SM2[L+1],
		int graph[MAX_VERTICES][MAX_VERTICES], 
		int graphMaps[MAX_VERTICES][MAX_VERTICES]) 
{
	int i,j;
	int ip,jp;
	double phi,I;

    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the IM/SM1/SM2 */

    /* Auxiliary variables */
    int iErr;

	/* Initialize graph to all zeros, and graphMaps to all -1 */
	for(i=0; i<nCells; i++)
	{
		for(j=0; j<nCells; j++)
		{
			graph[i][j] = 0;
			graphMaps[i][j] = -1;
		}
	}

	/* Add (directed) edges corresponding to SM1, and assign them a distance of
	 * 6 time units. */
	for(i=0; i<nCellsI; i++)
	{
		for(j=0; j<nCellsPhi; j++)
		{
			cell2pt(i,j,&I,&phi);

			/* Compute SM1 */
            iErr=SM(N, L, ipA, ipB, ipOmega, I, phi, &Ip, &phip);
            if(iErr)
            {
                fprintf(stderr, 
                "diffusion_shortest_path: Error computing the SM1 at I=%f, phi=%f\n", I, phi);
                exit(EXIT_FAILURE);
            }
			pt2cell(Ip,phip,&ip,&jp);

			/* distance between cells (i,j) and (ip,jp) = 6 (time spent by SM1)
			 * */
			//graph[i*nCellsI+j][ip*nCellsI+jp] = 6;
			graph[ip*nCellsI+jp][i*nCellsI+j] = 6;

			/* map applied to go from (i,j) to (ip,jp) = SM1 */
			//graphMaps[i*nCellsI+j][ip*nCellsI+jp] = 1;
			graphMaps[ip*nCellsI+jp][i*nCellsI+j] = 1;
		}
	}

	/* Add (directed) edges corresponding to SM2, and assign them a distance of
	 * 6 time units. */
	for(i=0; i<nCellsI; i++)
	{
		for(j=0; j<nCellsPhi; j++)
		{
			cell2pt(i,j,&I,&phi);

			/* Compute SM2 */
            iErr=SM(N, L, ipA_SM2, ipB_SM2, ipOmega_SM2, I, phi, &Ip, &phip);
            if(iErr)
            {
                fprintf(stderr, 
                "diffusion_shortest_path: Error computing the SM2 at I=%f, phi=%f\n", I, phi);
                exit(EXIT_FAILURE);
            }
			pt2cell(Ip,phip,&ip,&jp);

			/* distance between cells (i,j) and (ip,jp) = 6 (time spent by SM2)
			 * */
			//graph[i*nCellsI+j][ip*nCellsI+jp] = 6;
			graph[ip*nCellsI+jp][i*nCellsI+j] = 6;

			/* map applied to go from (i,j) to (ip,jp) = SM2 */
			//graphMaps[i*nCellsI+j][ip*nCellsI+jp] = 2;
			graphMaps[ip*nCellsI+jp][i*nCellsI+j] = 2;
		}
	}

	/* Finally, add (directed) edges corresponding to IM, and assign them a
	 * distance of 3 time units. Notice that IM applications take prececence
	 * over SM applications, in case there is both an IM edge and a SM edge
	 * between (i,j) and (ip,jp). */
	for(i=0; i<nCellsI; i++)
	{
		for(j=0; j<nCellsPhi; j++)
		{
			cell2pt(i,j,&I,&phi);

			/* Compute IM */
			IM(I, phi, &Ip, &phip);
			//phip = (phip>M_PI ? phip-M_PI : phip);
			pt2cell(Ip,phip,&ip,&jp);

			/* distance between cells (i,j) and (ip,jp) = 3 (time spent by IM)
			 * */
			//graph[i*nCellsI+j][ip*nCellsI+jp] = 3;
			graph[ip*nCellsI+jp][i*nCellsI+j] = 3;

			/* map applied to go from (i,j) to (ip,jp) = IM */
			//graphMaps[i*nCellsI+j][ip*nCellsI+jp] = 0;
			graphMaps[ip*nCellsI+jp][i*nCellsI+j] = 0;
		}
	}
}

void printGraph(int graph[MAX_VERTICES][MAX_VERTICES], 
		int graphMaps[MAX_VERTICES][MAX_VERTICES]) 
{
	int u,v;

	printf("Graph:\n");
	for(u=0; u<nCells; u++)
	{
		printf("Vertex %d: \n", u);
		for(v=0; v<nCells; v++)
		{
			printf("%d ", graph[u][v]);
		}
		printf("\n\n");
	}

	printf("Graph Maps:\n");
	for(u=0; u<nCells; u++)
	{
		printf("Vertex %d: \n", u);
		for(v=0; v<nCells; v++)
		{
			printf("%d ", graphMaps[u][v]);
		}
		printf("\n\n");
	}
}

int
main (int argc, char *argv[])
{
    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double It, phit;    /* Target point whose cell we want to reach */

    double ipA[N+1][L+1];   /* polyn interp of Fourier coeffs A_n(I) */
    double ipB[N+1][L+1];   /* polyn interp of Fourier coeffs B_n(I) */
    double ipOmega[L+1]; 	/* polyn interp of omega(I) */

    double ipA_SM2[N+1][L+1];   /* polyn interp of Fourier coeffs A_n(I) */
    double ipB_SM2[N+1][L+1];   /* polyn interp of Fourier coeffs B_n(I) */
    double ipOmega_SM2[L+1]; 	/* polyn interp of omega(I) */

    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the IM/SM */

	/* graph[i][j] = distance from vertex i to vertex j */
	int graph[MAX_VERTICES][MAX_VERTICES];

	/* graphMaps[i][j] = map needed to go from vertex i to vertex j 
	 * Possible maps are: IM = 0, SM1 = 1, SM2 = 2 */
	int graphMaps[MAX_VERTICES][MAX_VERTICES];

	int prev[MAX_VERTICES];

	int i,j;	/* (i,j) = source cell */
	int ip,jp;	/* (ip, jp) = target cell */

	/* Source and target vertices */
	int source, target;

	/* next vertex */
	int current, next;	

    /* auxiliary vars */
	double phi_old;
	int map, iErr;

    if(argc != 5)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s I phi \
				I_target phi_target\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    I = atof(argv[1]);	    /* scaled action level, e.g. I=2 */
    phi = atof(argv[2]);	/* \phi */

    It = atof(argv[3]);	    /* I_target */
    phit = atof(argv[4]);	/* \phi_target */

    /* Read FP series (polyn interp) from file */
    read_FP(N,L,SM1,ipA,ipB);
    read_FP(N,L,SM2,ipA_SM2,ipB_SM2);

    /* Read Polynomial series from file */
    read_P(L,ipOmega_FILE,ipOmega);
    read_P(L,ipOmega_FILE_SM2,ipOmega_SM2);

	/* Initialize adjacency matrix for the graph */
	initGraph(ipA,ipB,ipOmega,ipA_SM2,ipB_SM2,ipOmega_SM2,graph,graphMaps);

	//printGraph(graph,graphMaps);

	pt2cell(I,phi,&i,&j);
	source = i*nCellsI+j;
	//printf("Source cell: (%d,%d) -> Source vertex: %d\n",i,j,source);

	pt2cell(It,phit,&ip,&jp);
	target = ip*nCellsI+jp;
	//printf("Target cell: (%d,%d) -> Target vertex: %d\n",ip,jp,target);

	current = source;
    //while(current != target)
    //while(fabs(I-It)+fabs(phi-phit)>0.5)
    while(fabs(I-It)>0.5)
    {
		// Perform Dijkstra's algorithm
		dijkstra(graph, target, current, nCells, prev);

		next = prev[current];
		if(next == -1)
		{
			printf("No path from current vertex to target! Exiting\n");
			exit(EXIT_FAILURE);
		}
		/* The next vertex in the shortest path is `next' */

		map = graphMaps[next][current];
		if(map == 0)
		{
			/* Compute the IM: (I, phi) -> (Ip, phip) */
			IM(I, phi, &Ip, &phip);
			printf("%f %f %f %f %s\n", I, phi, Ip, phip, "IM");

			I = Ip;
			phi_old = phi;
			phi = phip;

			/* If angle phi wrapped around \pi, print newline. 
			   This is a trick for correctly plotting line segments in
			   diffusion_SM2.plt.
			 */
			//if(phi_old<M_PI/2 && phi>M_PI/2) printf("\n");
		}
		else if(map == 1)
		{
			/* Compute SM1 */
            iErr=SM(N, L, ipA, ipB, ipOmega, I, phi, &Ip, &phip);
            if(iErr)
            {
                fprintf(stderr, 
                "diffusion_shortest_path: Error computing the SM1 at I=%f, phi=%f\n", I, phi);
                exit(EXIT_FAILURE);
            }
			printf("%f %f %f %f %s\n", I, phi, Ip, phip, "SM1");

			I = Ip;
			phi = phip;
		}
		else	/* SM2 */
		{
			/* Compute SM2 */
            iErr=SM(N, L, ipA_SM2, ipB_SM2, ipOmega_SM2, I, phi, &Ip, &phip);
            if(iErr)
            {
                fprintf(stderr, 
                "diffusion_shortest_path: Error computing the SM2 at I=%f, phi=%f\n", I, phi);
                exit(EXIT_FAILURE);
            }
			printf("%f %f %f %f %s\n", I, phi, Ip, phip, "SM2");

			I = Ip;
			phi = phip;
		}

		/* Update current vertex */
		pt2cell(I,phi,&i,&j);
		current = i*nCellsI+j;
    }

    /* Print last iterate */
    if(map == 0)
        printf("%f %f %s\n", I, phi, "IM");
    else if(map == 1)
        printf("%f %f %s\n", I, phi, "SM1");
    else
        printf("%f %f %s\n", I, phi, "SM2");

    return 0;
}
