/** \file FP_module.c
  * \brief Functions to compute Fourier-Polynomial series and write it to file. Given \f$ (I,\phi') \f$, find \f$ pd{L^*}{\phi'} \f$.
  *
  * NOTES: 
  *		Fourier coeffs are read from files coeffs_*.res, which were generated
  *		by fft.sh
  *
  *		Do the same for the second scattering map, reading coeffs from files
  *		coeffs_*_SM2.res, and writing coeffs to ipA_SM2.res and ipB_SM2.res.
  *
  * CALLED BY: FP.c, FP_error.c	
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <gsl/gsl_multifit.h>	// Multi-parameter Linear Regression
#include "FP_module.h"			// SM_t

static const char A2_FILE[] = "A2.res";
static const char B2_FILE[] = "B2.res";
static const char A4_FILE[] = "A4.res";
static const char B4_FILE[] = "B4.res";
static const char ipA_FILE[] = "ipA.res";	// Interpolating Polynomial of An
static const char ipB_FILE[] = "ipB.res";

static const char A2_FILE_SM2[] = "A2_SM2.res";
static const char B2_FILE_SM2[] = "B2_SM2.res";
static const char A4_FILE_SM2[] = "A4_SM2.res";
static const char B4_FILE_SM2[] = "B4_SM2.res";
static const char ipA_FILE_SM2[] = "ipA_SM2.res";
static const char ipB_FILE_SM2[] = "ipB_SM2.res";

void write_Fourier_all_tori(size_t ntori, size_t nfour, 
		double coefs_all[ntori][nfour], int four, const char *filename);

/** 
 * \brief Read Fourier coefficients from files coeffs_*.res.
 *
 * Read Fourier coefficients from files coeffs_*.res, which were generated by
 * fft.sh. Since the scattering map is \f$\pi\f$-periodic, odd Fourier
 * coefficients should be zero. Thus we decide to zero all odd coefficients to
 * impose that the Fourier series preserves the symmetry.
 *
 * Fourier coefficients \f$ A_n(0), B_n(0) \f$ are zero, so we set them
 * separately.
 *
 * @param[in]   ntori	Number of tori
 * @param[in]   nfour	Number of Fourier coefficients computed by FFT
 * @param[in]   SM		SM1 or SM2
 *
 * @param[out]  A_all	Table containing for each torus I, its Fourier coefs.
 * A_n.
 * @param[out]  B_all	Table containing for each torus I, its Fourier coefs.
 * B_n.
 */
void read_Fourier_coefs(size_t ntori, size_t nfour, SM_t SM,
		double A_all[ntori][nfour], double B_all[ntori][nfour]) 
{
	/* auxiliary variables */
	char filename[100];
	double *Ap, *Bp;
	FILE *fp;
	int coeff_num;
	int i,j;

	/* Fourier coefficients \f$ A_n(0), B_n(0) \f$ of first torus are known to
	 * be zero, so we set them separately. */
	for(j=0; j<nfour; j++)
		A_all[0][j] = 0;

	/* Read Fourier coeffs of all other tori from file */
	for(int i=1; i<ntori; i++)
	{
		if(SM == SM1) sprintf(filename, "coeffs_%d.res", i+1);
		else sprintf(filename, "coeffs_%d_SM2.res", i+1);

		Ap = A_all[i];
		Bp = B_all[i];

		fp = fopen(filename, "r");
		while(fscanf(fp,"%d %le %le", &coeff_num, Ap, Bp) != EOF) {
			/* Zero all odd Fourier coefficients */
			if(coeff_num % 2 != 0)	
			{
				*Ap=0; 
				*Bp=0;
			}

			/* advance pointers */
			Ap ++; Bp ++;

		}
		fclose(fp);
	}

	if(SM == SM1)
	{
		write_Fourier_all_tori(ntori, nfour, A_all, 2, A2_FILE); 
		write_Fourier_all_tori(ntori, nfour, B_all, 2, B2_FILE); 
		write_Fourier_all_tori(ntori, nfour, A_all, 4, A4_FILE); 
		write_Fourier_all_tori(ntori, nfour, B_all, 4, B4_FILE); 
	}
	else	// SM2
	{	
		write_Fourier_all_tori(ntori, nfour, A_all, 2, A2_FILE_SM2); 
		write_Fourier_all_tori(ntori, nfour, B_all, 2, B2_FILE_SM2); 
		write_Fourier_all_tori(ntori, nfour, A_all, 4, A4_FILE_SM2); 
		write_Fourier_all_tori(ntori, nfour, B_all, 4, B4_FILE_SM2); 
	}
}

/** 
 * \brief Write Fourier coefficient `n' of each tori (torus=0,1,2,...,7).
 *
 * The file generated (e.g. A0.res) is used for inspection and plotted in
 * interp_poly_A2.plt.
 *
 * @param[in]   ntori	Number of tori
 * @param[in]   nfour	Number of Fourier coefficients computed by FFT
 * @param[in]	coefs_all	Table containing for each torus I, its Fourier coefs.
 * A_n/B_n.
 *
 * @param[in]	four	Fourier coefficient to write.
 *
 * @param[in]	filename	Name of file to write to (e.g. A0.res).
 */
void write_Fourier_all_tori(size_t ntori, size_t nfour, 
		double coefs_all[ntori][nfour], int four, const char *filename) 
{
	const int n=ntori;
	const int j=four;

	double x[n], y[n];

	/* auxiliary variables */
	FILE *fp;

	fp = fopen(filename, "w");

	/* Write coefs */
	for(int i=0; i<n; i++)
	{
		x[i] = i;			/* I */
		y[i] = coefs_all[i][j];	/* A_j(I) or B_j(I) */
		fprintf(fp, "%f %f\n", x[i], y[i]);
	}

	fclose(fp);
}

typedef struct
{
    double *d;
    double *coef;
    double *work;
}
polynomial_state_t;

/** 
 * \brief Compute FP series of degree (N,L), i.e. polynomial fit of Fourier coeffs A(I) or B(I).
 *
 * @param[in]   ntori	Number of tori
 * @param[in]   nfour	Number of Fourier coefficients computed by FFT
 * @param[in]   coefs_all	Table containing for each torus I, its Fourier coefs. A_n (or B_n).
 * @param[in]   N		Degree of Fourier series (= nfour-1)
 * @param[in]   L		Degree of Polynomial series (<= ntori-1)
 * @param[out]  C		Fourier-Poynomial series (coefs of polynomial fit).
 * 
 */
void compute_FP(size_t ntori, size_t nfour, double coefs_all[ntori][nfour], int
		N, int L, double C[N+1][L+1]) 
{
	const int n=ntori;		// number of data points (per Fourier coef)
	double chisq;
	gsl_matrix *X, *cov;	// model matrix, covariance matrix
	gsl_vector *y, *c;		// values, coefficients (c0,c1,...,cL)

	// auxiliary vars
	double xi, yi, xi_accum;

	X = gsl_matrix_alloc(n,L+1);
	y = gsl_vector_alloc(n);
	c = gsl_vector_alloc(L+1);
	cov = gsl_matrix_alloc(L+1,L+1);

	for(int j=0; j<N+1; j++)
    {
		/* input curve */
		for(int i=0; i<n; i++)
        {
			xi = (double)i;			/* I */
            yi = coefs_all[i][j];	/* A_j(I) or B_j(I) */
			xi_accum = 1.0;

			gsl_matrix_set(X, i, 0, xi_accum);
			for(int k=1; k<L+1; k++)
			{
				xi_accum = xi_accum*xi;
				gsl_matrix_set(X, i, k, xi_accum);
			}

			gsl_vector_set(y, i, yi);
        }
      
		gsl_multifit_linear_workspace * work = gsl_multifit_linear_alloc (n,
				L+1);
		gsl_multifit_linear (X, y, c, cov, &chisq, work);
		gsl_multifit_linear_free (work);

		for(int k=0; k<L+1; k++)
			C[j][k] = gsl_vector_get(c,k);
    }

	gsl_matrix_free (X); 
	gsl_vector_free (y); 
	gsl_vector_free (c); 
	gsl_matrix_free (cov);
}

/** 
 * \brief Write FP series to file.
 *
 * @param[in]	N   Degree of the Fourier series
 * @param[in]	L   Degree of the Polynomial series
 * @param[in]	SM	SM1 or SM2
 *
 * @param[in]	ipA     Fourier-Polynomial series
 * @param[in]	ipB     Fourier-Polynomial series
 *
 * \remark In the future, write N,L to file as well.
 */
void write_FP(size_t N, size_t L, SM_t SM, double ipA[N+1][L+1], double
		ipB[N+1][L+1])
{
	FILE *fpA;
	FILE *fpB;
	if(SM==SM1)
	{
		fpA = fopen(ipA_FILE, "w");
		fpB = fopen(ipB_FILE, "w");
	}
	else // SM2
	{
		fpA = fopen(ipA_FILE_SM2, "w");
		fpB = fopen(ipB_FILE_SM2, "w");
	}
    for(int i=0; i<N+1; i++)
    {
        for(int j=0; j<L; j++)
        {
            fprintf(fpA, "%.15le ", ipA[i][j]);
            fprintf(fpB, "%.15le ", ipB[i][j]);
        }
		// Last coefficient, j == L, is treated differently, since we don't
		// want to add a space character after it.
        fprintf(fpA, "%.15le\n", ipA[i][L]);
        fprintf(fpB, "%.15le\n", ipB[i][L]);
    }
    fclose(fpA);
    fclose(fpB);
}

/** 
 * \brief Read FP series from file.
 *
 * @param[in]   N   Degree of the Fourier series
 * @param[in]   L   Degree of the Polynomial series
 * @param[in]   SM		SM1 or SM2
 *
 * @param[out]  ipA     Fourier-Polynomial series
 * @param[out]  ipB     Fourier-Polynomial series
 *
 * \remark In the future, read N,L from file as well.
 */
void read_FP(size_t N, size_t L, SM_t SM, double ipA[N+1][L+1], double
		ipB[N+1][L+1])
{
	FILE *fpA;
	FILE *fpB;
	if(SM==SM1)
	{
		fpA = fopen(ipA_FILE, "r");
		fpB = fopen(ipB_FILE, "r");
	}
	else // SM2
	{
		fpA = fopen(ipA_FILE_SM2, "r");
		fpB = fopen(ipB_FILE_SM2, "r");
	}

	int nIt;	// Number of read items
    for(int i=0; i<N+1; i++)
    {
        for(int j=0; j<L; j++)
        {
            nIt = fscanf(fpA, "%le ", &(ipA[i][j]));
            nIt = fscanf(fpB, "%le ", &(ipB[i][j]));
        }
		// Last coefficient, j == L, is treated differently, since we don't
		// want to add a space character after it.
        nIt = fscanf(fpA, "%le\n", &(ipA[i][L]));
        nIt = fscanf(fpB, "%le\n", &(ipB[i][L]));
    }
    fclose(fpA);
    fclose(fpB);
}

/** 
 * \brief Evaluate Fourier coefs A_j (or B_j) at I using polynomial interpolation.
 *
 * @param[in]   N   Degree of the Fourier series.
 * @param[in]   L   Degree of the Polynomial series.
 * @param[in]   C	Fourier-Poynomial series (coefs of polynomial fit).
 * @param[in]   I   Action at which we want to evaluate.
 * @param[out]  A   Fourier coefs A_j(I) (or B_j(I)).
 */
void coefs_eval(size_t N, size_t L, double C[N+1][L+1], double I, double
		A[N+1]) 
{
	for(int j=0; j<=N; j++)
    {
        /* Interpolate F. coef A_j at I */
        assert(L<=7);
        switch(L)
        {
            case 0:
                A[j] = C[j][0];
                break;
            case 1:
                A[j] = C[j][0] + C[j][1]*I;
                break;
            case 2: 
                A[j] = C[j][0] + C[j][1]*I + C[j][2]*I*I;
                break;
            case 3: 
                A[j] = C[j][0] + C[j][1]*I + C[j][2]*I*I + C[j][3]*I*I*I;
                break;
            case 4: 
                A[j] = C[j][0] + C[j][1]*I + C[j][2]*I*I + C[j][3]*I*I*I \
					   + C[j][4]*I*I*I*I;
				break;
            case 5: 
                A[j] = C[j][0] + C[j][1]*I + C[j][2]*I*I + C[j][3]*I*I*I \
					   + C[j][4]*I*I*I*I + C[j][5]*I*I*I*I*I;
				break;
            case 6: 
				A[j] = C[j][0] + C[j][1]*I + C[j][2]*I*I + C[j][3]*I*I*I +
					C[j][4]*I*I*I*I + C[j][5]*I*I*I*I*I + C[j][6]*I*I*I*I*I*I;
				break;
            case 7: 
				A[j] = C[j][0] + C[j][1]*I + C[j][2]*I*I + C[j][3]*I*I*I +
					C[j][4]*I*I*I*I + C[j][5]*I*I*I*I*I + C[j][6]*I*I*I*I*I*I +
					C[j][7]*I*I*I*I*I*I*I;
                break;
            default:
                break;
        }
    }
}

/** 
 * \brief Evaluate derivative of Fourier coefs A_j (or B_j) at I using Polynomial interpolation.
 *
 * @param[in]   N   Degree of the Fourier series.
 * @param[in]   L   Degree of the Polynomial series.
 * @param[in]   ipA Complete Fourier-Polynomial series.
 * @param[in]   I   Action at which we want to evaluate.
 * @param[out]  Ap   Derivative of Fourier coefs A_j(I) (or B_j(I)).
 */
void dcoefs_eval(size_t N, size_t L, double ipA[N+1][L+1], double I, double
		Ap[N+1]) 
{
	for(int j=0; j<=N; j++)
    {
        /* Interpolate F. coef A_j' at I */
        assert(L<=7);
        switch(L)
        {
            case 0:
                Ap[j] = 0;
                break;
            case 1:
                Ap[j] = ipA[j][1];
                break;
            case 2: 
                Ap[j] = ipA[j][1] + 2*ipA[j][2]*I;
                break;
            case 3:
				Ap[j] = ipA[j][1] + 2*ipA[j][2]*I + 3*ipA[j][3]*I*I;
                break;
            case 4:
				Ap[j] = ipA[j][1] + 2*ipA[j][2]*I + 3*ipA[j][3]*I*I +
					4*ipA[j][4]*I*I*I;
                break;
            case 5:
				Ap[j] = ipA[j][1] + 2*ipA[j][2]*I + 3*ipA[j][3]*I*I +
					4*ipA[j][4]*I*I*I + 5*ipA[j][5]*I*I*I*I;
                break;
            case 6:
				Ap[j] = ipA[j][1] + 2*ipA[j][2]*I + 3*ipA[j][3]*I*I +
					4*ipA[j][4]*I*I*I + 5*ipA[j][5]*I*I*I*I +
					6*ipA[j][6]*I*I*I*I*I;
                break;
            case 7:
				Ap[j] = ipA[j][1] + 2*ipA[j][2]*I + 3*ipA[j][3]*I*I +
					4*ipA[j][4]*I*I*I + 5*ipA[j][5]*I*I*I*I +
					6*ipA[j][6]*I*I*I*I*I + 7*ipA[j][7]*I*I*I*I*I*I;
                break;
            default:
                break;
        }
    }
}

/** 
 * \brief Evaluate SECOND derivative of Fourier coefs A_j (or B_j) at I using Taylor interpolation.
 *
 * \important THIS FUNCTION NEEDS TO CHANGE AFTER MOVE TO F-P SEIES!!
 *
 * @param[in]   nfour   Max degree of the Fourier series = nfour-1.
 * @param[in]   ntori   Max degree of the Taylor series = ntori-1.
 * @param[in]   ipA Complete Fourier-Taylor series (div. difs. of Fourier coeffs).
 * @param[in]   N   Degree of the Fourier series.
 * @param[in]   M   Degree of the Taylor series.
 * @param[in]   I   Action at which we want to evaluate.
 * @param[out]  App   SECOND derivative of Fourier coefs A_j(I) (or B_j(I)).
 */
void d2coefs_eval(size_t nfour, size_t ntori, double ipA[nfour][ntori], 
		size_t N, size_t M, double I, double App[N+1]) 
{
	const double I0=0;
	const double I1=1;
	const double I2=2;
	const double I3=3;
	const double I4=4;
	const double I5=5;
	const double I6=6;

    double d0, d1, d2, d3, d4, d5, d6, d7;
	for(int j=0; j<=N; j++)
    {
		d0 = ipA[j][0];
		d1 = ipA[j][1];
		d2 = ipA[j][2];
		d3 = ipA[j][3];
		d4 = ipA[j][4];
		d5 = ipA[j][5];
		d6 = ipA[j][6];
		d7 = ipA[j][7];

        /* Interpolate F. coef A_j' at I */
        assert(M<=7);
        switch(M)
        {
            case 0:
            case 1:
                App[j] = 0;
                break;
            case 2:
                App[j] = 2*d2;
                break;
            case 3: 
                App[j] = 2*d2 + 2*d3*((I-I0)+(I-I1)+(I-I2));
                break;
            case 4:
            case 5:
            case 6:
            case 7:
                App[j] = 2*d2 + 2*d3*((I-I0)+(I-I1)+(I-I2)) + 
					2*d4*((I-I0)*(I-I1)+(I-I0)*(I-I2)+(I-I0)*(I-I3)+
							(I-I1)*(I-I2)+(I-I1)*(I-I3)+(I-I2)*(I-I3));
                break;
            default:
                break;
        }
    }
}

/**
 * \brief Given \f$(I,\phi')\f$, find \f$pd{\widetilde{L}}{\phi'}(I,\phi)\f$
 *
 * @param[in] N		Degree of Fourier series
 * @param[in] A		A = (A_0, A_1, ..., A_N), Fourier coeffs evaluated at I
 * @param[in] B		B = (B_0, B_1, ..., B_N), Fourier coeffs evaluated at I
 * @param[in] phi	Angle where to evaluate the partial derivative.
 */
double dL_dphi(size_t N, double A[N+1], double B[N+1], double phi)
{
	double res = 0.0;
	for(int j=1; j<=N; j++)
	{
		res = res + (A[j]*cos(j*phi) + B[j]*sin(j*phi));
	}
	return res;
}

/**
 * \brief Given \f$ (I,\phi') \f$, find \f$ pd{\widetilde{L}}{I}(I,\phi) \f$
 *
 * @param[in] N		Degree of Fourier series
 * @param[in] Ap	A' = (A_0', A_1', ..., A_N'), A_k' := dA_k/dI(I)
 * @param[in] Bp	B' = (B_0', B_1', ..., B_N'), B_k' := dB_k/dI(I)
 * @param[in] phi	Angle where to evaluate the partial derivative.
 */
double dL_dI(size_t N, double Ap[N+1], double Bp[N+1], double phi)
{
	double res = 0.0;
	for(int j=1; j<=N; j++)
	{
		res = res + (Ap[j]/j*sin(j*phi) - Bp[j]/j*cos(j*phi));
	}
	return res;
}

/**
 * \brief Given \f$ (I,\phi') \f$, find \f$ pd[2]{\widetilde{L}}{I}(I,\phi) \f$
 *
 * @param[in] N		Degree of Fourier series
 * @param[in] App	A'' = (A_0'', A_1'', ..., A_N''), A_k'' := d^2A_k/dI^2(I)
 * @param[in] Bpp	B'' = (B_0'', B_1'', ..., B_N''), B_k'' := d^2B_k/dI^2(I)
 * @param[in] phi	Angle where to evaluate the second partial derivative.
 */
double d2L_dI(size_t N, double App[N+1], double Bpp[N+1], double phi)
{
	double res = 0.0;
	for(int j=1; j<=N; j++)
	{
		res = res + (App[j]/j*sin(j*phi) - Bpp[j]/j*cos(j*phi));
	}
	return res;
}

/**
 * \brief Given \f$(I,\phi')\f$, find \f$md{\widetilde{L}}{2}{\phi'}{1}{I}{1}(I,\phi')\f$
 *
 * @param[in] N		Degree of Fourier series
 * @param[in] Ap	A' = (A_0', A_1', ..., A_N'), A_k' := dA_k/dI(I)
 * @param[in] Bp	B' = (B_0', B_1', ..., B_N'), B_k' := dB_k/dI(I)
 * @param[in] phi	Angle where to evaluate the partial derivative.
 */
double d2L_dphidI(size_t N, double Ap[N+1], double Bp[N+1], double phi)
{
	double res = 0.0;
	for(int j=1; j<=N; j++)
	{
		res = res + (Ap[j]*cos(j*phi) + Bp[j]*sin(j*phi));
	}
	return res;
}

/**
 * \brief Given \f$(I,\phi')\f$, find \f$\widetilde{L}(I,\phi')\f$
 *
 * @param[in] N		Degree of Fourier series
 * @param[in] A		A = (A_0, A_1, ..., A_N), Fourier coeffs evaluated at I
 * @param[in] B		B = (B_0, B_1, ..., B_N), Fourier coeffs evaluated at I
 * @param[in] phip	Angle where to evaluate the function.
 */
double widetildeL(size_t N, double A[N+1], double B[N+1], double phip)
{
	double res = 0.0;
	for(int n=1; n<=N; n++)
	{
		res = res - B[n]/n*cos(n*phip) + A[n]/n*sin(n*phip);
	}
	return res;
}

