/** \file P_module.c
  * \brief Functions to compute Polynomial series of \f$\omega(I)\f$ and write it to file.
  *
  * NOTES: 
  *		Values of \f$\omega(I=1..7)\f$ are read from file
  *		omega_all.res, which was generated by omega_all.sh
  *
  * CALLED BY: P.c, P_error.c	
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <gsl/gsl_multifit.h>   // Multi-parameter Linear Regression

/** Constrain angle \f$ x \in [-2\pi, 2\pi) \f$ to be in \f$ [0, 2\pi) \f$.
  * Then, further constrain angle to \f$ [0, \pi) \f$.
 *
 */
double constrainAngle(double x){
    x = fmod(x,2*M_PI);
    if (x < 0)
        x += 2*M_PI;

	/* Further constrain to [0,\pi) */
	if (x>= M_PI) 
		x -= M_PI;
    return x;
}

/**
 * \brief Read omega values from file.
 *
 * Read omega values from file fn, which were generated by omega_all.sh.
 *
 * @param[in]   ntori   Number of tori
 * @param[in]   fn      Filename to read from
 *
 * @param[out]  omega_all   Table containing for each torus I, its omega value
 * \f$ \omega(I) \f$.
 */
void read_omegas(size_t ntori, const char *fn, double omega_all[ntori]) 
{
	/* auxiliary variables */
	FILE *fp;
	double I;

    fp = fopen(fn, "r");
	for(int i=0; i<ntori; i++)
	{
		fscanf(fp,"%le %le", &I, &(omega_all[i]));
	}
    fclose(fp);
}

typedef struct
{
    double *d;
    double *coef;
    double *work;
}
polynomial_state_t;

/** 
 * \brief Compute Polynomial series of degree \f$L\f$ for \f$\omega(I)\f$.
 *
 * @param[in]   ntori		Number of tori (=7)
 * @param[in]   omega_all	Table containing for each torus I, \f$\omega(I)\f$.
 * @param[in]   L			Degree of Polynomial series (<= ntori-1).
 *
 * @param[out]  ip  Polynomial series (coefs of polynomial fit of omega).
 * 
 */
void compute_P(size_t ntori, double omega_all[ntori], int L, double ip[L+1]) 
{
	const int n=ntori;
    double chisq;
    gsl_matrix *X, *cov;    // model matrix, covariance matrix
    gsl_vector *y, *c;      // values, coefficients (c0,c1,...,cL)
    
    // auxiliary vars
    double xi, yi, xi_accum;

    X = gsl_matrix_alloc(n,L+1);
    y = gsl_vector_alloc(n);
    c = gsl_vector_alloc(L+1);
    cov = gsl_matrix_alloc(L+1,L+1);

    /* input curve */
    for(int i=0; i<n; i++)
    {
	    xi = (double)(i+1); 	/* I */
		yi = omega_all[i]; 		/* \omega(I) */
		xi_accum = 1.0;

		gsl_matrix_set(X, i, 0, xi_accum);
		for(int k=1; k<L+1; k++)
		{
			xi_accum = xi_accum*xi;
			gsl_matrix_set(X, i, k, xi_accum);
		}

		gsl_vector_set(y, i, yi);

    }
  
	gsl_multifit_linear_workspace * work = gsl_multifit_linear_alloc (n,
			L+1);
	gsl_multifit_linear (X, y, c, cov, &chisq, work);
	gsl_multifit_linear_free (work);

	for(int k=0; k<L+1; k++)
		ip[k] = gsl_vector_get(c,k);

    gsl_matrix_free (X);
    gsl_vector_free (y);
    gsl_vector_free (c);
    gsl_matrix_free (cov);
}

/** 
 * \brief Write Polynomial series to file.
 *
 * @param[in]   L 		Degree of the Polynomial series
 * @param[in]   ip      Polynomial series
 * @param[in]   fn      Filename to write to.
 *
 * \remark In the future, write L to file as well.
 */
void write_P(size_t L, double ip[L+1], const char *fn)
{
    FILE *fp = fopen(fn, "w");
    for(int j=0; j<L+1; j++)
    {
        fprintf(fp, "%.15le ", ip[j]);
    }
    fprintf(fp, "\n");
    fclose(fp);
}

/** 
 * \brief Read Polynomial series from file.
 *
 * @param[in]   L 		Degree of the Polynomial series
 * @param[in]   fn		Filename to read from
 *
 * @param[out]  ip      Polynomial series
 */
void read_P(size_t L, const char *fn, double ip[L+1])
{
    FILE *fp = fopen(fn, "r");

	int nIt;	// Number of read items
    for(int j=0; j<L+1; j++)
    {
        nIt = fscanf(fp, "%le ", &(ip[j]));
    }
    nIt = fscanf(fp, "\n");
    fclose(fp);
}

/** 
 * \brief Evaluate omega at I using Polynomial interpolation.
 *
 * @param[in]   L 		Degree of the Polynomial series
 * @param[in]   ip      Polynomial series (coefs of polynomial fit)
 * @param[in]   I       Action at which we want to evaluate.
 *
 * @param[out]  omega_p     On exit, it points to the value omega(I).
 */
void omega_eval(size_t L, double ip[L+1], double I, double *omega_p) 
{
    double d0, d1, d2, d3, d4, d5, d6;
    d0 = ip[0];
    d1 = ip[1];
    d2 = ip[2];
    d3 = ip[3];
    d4 = ip[4];
    d5 = ip[5];
    d6 = ip[6];

    /* Interpolate omega at I */
    assert(L<=6);
    switch(L)
    {
        case 0:
            *omega_p = d0;
            break;
        case 1:
            *omega_p = d0 + d1*I;
            break;
        case 2: 
            *omega_p = d0 + d1*I + d2*I*I;
            break;
        case 3:
			*omega_p = d0 + d1*I + d2*I*I + d3*I*I*I;
            break;
        case 4:
			*omega_p = d0 + d1*I + d2*I*I + d3*I*I*I + d4*I*I*I*I;
            break;
	    case 5:
			*omega_p = d0 + d1*I + d2*I*I + d3*I*I*I + d4*I*I*I*I +
				d5*I*I*I*I*I;
			break;
		case 6:
			*omega_p = d0 + d1*I + d2*I*I + d3*I*I*I + d4*I*I*I*I +
				d5*I*I*I*I*I + d6*I*I*I*I*I*I;
			break;
        default:
            break;
    }
}

/** 
 * \brief Evaluate derivative of omega at I using derivative of Polynomial series.
 *
 * \important THIS FUNCTION NEEDS TO CHANGE AFTER MOVE TO F-P SEIES!!
 *
 * @param[in]   ntori   Max degree of the Polynomial series of omega = ntori-1.
 * @param[in]   dd      Complete Polynomial series (div. difs. of omega).
 * @param[in]   M       Degree of the Polynomial series.
 * @param[in]   I       Action at which we want to evaluate.
 *
 * @param[out]  omega_p     On exit, it points to the value omega'(I).
 */
void domega_eval(size_t ntori, double dd[ntori], size_t M, double I, double
        *domega_p) 
{
    const double I0=1;
    const double I1=2;
    const double I2=3;
    const double I3=4;
    const double I4=5;
    const double I5=6;

    double d0, d1, d2, d3, d4, d5, d6;
    d0 = dd[0];
    d1 = dd[1];
    d2 = dd[2];
    d3 = dd[3];
    d4 = dd[4];
    d5 = dd[5];
    d6 = dd[6];

    /* Compute derivative of omega at I */
    assert(M<=6);
    switch(M)
    {
        case 0:
            *domega_p = 0;
            break;
        case 1:
            *domega_p = d1;
            break;
        case 2: 
            *domega_p = d1 + d2*((I-I1)+(I-I0));
            break;
        case 3:
            *domega_p = d1 + d2*((I-I1)+(I-I0)) +
                d3*((I-I1)*(I-I2) + (I-I0)*(I-I2) + (I-I0)*(I-I1));
            break;
        case 4:
            *domega_p =  d1 + d2*((I-I1)+(I-I0)) +
                d3*((I-I1)*(I-I2) + (I-I0)*(I-I2) + (I-I0)*(I-I1)) +
                d4*((I-I1)*(I-I2)*(I-I3) + (I-I0)*(I-I2)*(I-I3) +
                        (I-I0)*(I-I1)*(I-I3) + (I-I0)*(I-I1)*(I-I2));
            break;
        case 5:
            *domega_p =  d1 + 
                d2*((I-I1)+(I-I0)) +
                d3*((I-I1)*(I-I2) + (I-I0)*(I-I2) + (I-I0)*(I-I1)) +
                d4*((I-I1)*(I-I2)*(I-I3) + (I-I0)*(I-I2)*(I-I3) +
                        (I-I0)*(I-I1)*(I-I3) + (I-I0)*(I-I1)*(I-I2)) +
                d5*((I-I1)*(I-I2)*(I-I3)*(I-I4) + 
                        (I-I0)*(I-I2)*(I-I3)*(I-I4) +
                        (I-I0)*(I-I1)*(I-I3)*(I-I4) + 
                        (I-I0)*(I-I1)*(I-I2)*(I-I4) + 
                        (I-I0)*(I-I1)*(I-I2)*(I-I3));
            break;
        case 6:
            *domega_p =  d1 + 
                d2*((I-I1)+(I-I0)) +
                d3*((I-I1)*(I-I2) + (I-I0)*(I-I2) + (I-I0)*(I-I1)) +
                d4*((I-I1)*(I-I2)*(I-I3) + (I-I0)*(I-I2)*(I-I3) +
                        (I-I0)*(I-I1)*(I-I3) + (I-I0)*(I-I1)*(I-I2)) +
                d5*((I-I1)*(I-I2)*(I-I3)*(I-I4) + 
                        (I-I0)*(I-I2)*(I-I3)*(I-I4) +
                        (I-I0)*(I-I1)*(I-I3)*(I-I4) + 
                        (I-I0)*(I-I1)*(I-I2)*(I-I4) + 
                        (I-I0)*(I-I1)*(I-I2)*(I-I3)) +
                d6*((I-I1)*(I-I2)*(I-I3)*(I-I4)*(I-I5) + 
                        (I-I0)*(I-I2)*(I-I3)*(I-I4)*(I-I5) +
                        (I-I0)*(I-I1)*(I-I3)*(I-I4)*(I-I5) + 
                        (I-I0)*(I-I1)*(I-I2)*(I-I4)*(I-I5) + 
                        (I-I0)*(I-I1)*(I-I2)*(I-I3)*(I-I5) +
                        (I-I0)*(I-I1)*(I-I2)*(I-I3)*(I-I4));
            break;
        default:
            break;
    }
}

