/** \file SM.c
  * \brief Compute the scattering map \f$ (I', \phi') = \sigma(I,\phi) \f$.
  *
  *	We use the Fourier-Polynomial series of optimal degree (N=8,L=4).
  *
  *	\remark Fourier-Polynomial coeffs for the generating function are read from
  *	files ipA.res and ipB.res, which were generated by program FP.
  *
  *	\remark Polynomial coeffs for omega are read from ipOmega.res, which was
  *	generated by P.
  *
  * \attention Caller must specify which SM to use (SM1 or SM2) as a
  * command-line argument.
  *
  * USAGE:	./SM 1 2 0 (SM1, action I=2, phi=0)
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include "FP_module.h"
#include "P_module.h"
#include "SM_module.h"

static const char ipOmega_FILE[] = "ipOmega.res";
static const char ipOmega_FILE_SM2[] = "ipOmega_SM2.res";

int
main (int argc, char *argv[])
{
	const int nfour=65; 	/* Number of Fourier coeffs used in FFT */
	const int ntori=8;		/* Number of tori used in numerical SM */

    const int N = 8;    /* Degree of Fourier series */
    const int L = 4;    /* Degree of Taylor series */

    double ipA[N+1][L+1];   /* polyn interp of Fourier coeffs A_n(I) */
    double ipB[N+1][L+1];   /* polyn interp of Fourier coeffs B_n(I) */
    double ipOmega[L+1]; 	/* polyn interp of omega(I) */

	SM_t bSM;			/* Which SM (SM1 or SM2) */
    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the SM */

    /* auxiliary vars */
    int iSM;
    int iErr;

    if(argc != 4)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s SM scaled_I phi\n",
              argv[0]);
        exit(EXIT_FAILURE);
    }

	iSM = atoi(argv[1]);
    if(iSM==1)
        bSM = SM1;
    else
        bSM = SM2;

    I = atof(argv[2]);	    /* scaled action level, e.g. I=2 */
    phi = atof(argv[3]);	/* \phi */

    /* Read FP series (polyn interp) from file */
    read_FP(N,L,bSM,ipA,ipB);

    /* Read Polynomial series from file */
	if(bSM==SM1)	read_P(L,ipOmega_FILE,ipOmega);
	else			read_P(L,ipOmega_FILE_SM2,ipOmega);

	/* Compute the SM: (I, phi) -> (Ip, phip) */
    iErr=SM(N, L, ipA, ipB, ipOmega, I, phi, &Ip, &phip);
    if(iErr)
    {
        fprintf(stderr, 
        "SM: Error computing the SM at I=%f, phi=%f\n", I, phi);
        exit(EXIT_FAILURE);
    }

    printf("%f %f\n", Ip, phip);
    return 0;
}
