/** \file SM.c
  * \brief Compute the scattering map \f$ (I', \phi') = \sigma(I,\phi) \f$.
  *
  *	The degree (N,M) of the Fourier-Taylor series can be modified in the code.
  *
  * NOTES: 
  *		Fourier-Taylor coeffs for the generating function are read from files
  *		ddA.res and ddB.res, which were generated by FT. 
  *
  *		Taylor coeffs for omega are read from ddOmega.res, which was generated
  *		by T.
  *
  *     Caller must specify which SM to use (SM1 or SM2) as a command-line
  *     argument.
  *
  * USAGE:	./SM 1 2 0 (SM1, action I=2, phi=0)
  *
  * CALLED BY:	
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include "FT_module.h"
#include "T_module.h"
#include "SM_module.h"

static const char ddOmega_FILE[] = "ddOmega.res";
static const char ddOmega_FILE_SM2[] = "ddOmega_SM2.res";

int
main (int argc, char *argv[])
{
	const int nfour=65; 	/* Number of Fourier coeffs used in FFT */
	const int ntori=8;		/* Number of tori used in numerical SM */

	double ddA[nfour][ntori];	/* divided differences of Fourier coeffs A_n(I) */
	double ddB[nfour][ntori];	/* divided differences of Fourier coeffs B_n(I) */
    double ddOmega[ntori-1];      /* divided differences of omega(I) */

    const int N = 2;    /* Degree of Fourier series */
    const int M = 2;    /* Degree of Taylor series */

	SM_t bSM;			/* Which SM (SM1 or SM2) */
    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the SM */

    /* auxiliary vars */
    int iSM;

    if(argc != 4)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s SM scaled_I phi\n",
              argv[0]);
        exit(EXIT_FAILURE);
    }

	iSM = atoi(argv[1]);
    if(iSM==1)
        bSM = SM1;
    else
        bSM = SM2;

    I = atof(argv[2]);	    /* scaled action level, e.g. I=2 */
    phi = atof(argv[3]);	/* \phi */

    /* Read FT series (divided differences) from file */
    read_FT(nfour,ntori,bSM,ddA,ddB);

    /* Read Taylor series (divided differences) from file */
	if(bSM==SM1)	read_T(ntori-1,ddOmega_FILE,ddOmega);
	else			read_T(ntori-1,ddOmega_FILE_SM2,ddOmega);

	/* Compute the SM: (I, phi) -> (Ip, phip) */
	SM(nfour, ntori, ddA, ddB, ddOmega, N, M, I, phi, &Ip, &phip);
	
    printf("%f %f\n", Ip, phip);
    return 0;
}
