/** \file SM_given_I.c
  * \brief Given I, find the image under the scattering map of the torus T(I).
  *
  *	The degree (N,M) of the Fourier-Taylor series can be modified in the code.
  *
  * NOTES: 
  *		Fourier-Taylor coeffs for the generating function are read from files
  *		ddA.res and ddB.res, which were generated by FT. 
  *
  *		Taylor coeffs for omega are read from ddOmega.res, which was generated
  *		by T.
  *
  * USAGE:	./SM_given_I 2 > SM_I_2.dat
  *
  * CALLED BY: check_FourierTaylor.sh	
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>		// M_PI
#include "FT_module.h"	// SM_t SM1/SM2, read_FT
#include "T_module.h"
#include "SM_module.h"

static const int NPOINTS = 100;
static const char ddOmega_FILE[] = "ddOmega.res";

int
main (int argc, char *argv[])
{
	const int nfour=65; 	/* Number of Fourier coeffs used in FFT */
	const int ntori=8;		/* Number of tori used in numerical SM */

	double ddA[nfour][ntori];	/* divided differences of Fourier coeffs A_n(I) */
	double ddB[nfour][ntori];	/* divided differences of Fourier coeffs B_n(I) */
    double ddOmega[ntori-1];      /* divided differences of omega(I) */

    const int N = 2;    /* Degree of Fourier series */
    const int M = 2;    /* Degree of Taylor series */

    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the SM */

    if(argc != 2)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s scaled_I\n",
              argv[0]);
        exit(EXIT_FAILURE);
    }

    I = atof(argv[1]);	    /* scaled action level, e.g. I=2 */

    /* Read FT series (divided differences) from file */
    read_FT(nfour,ntori,SM1,ddA,ddB);

    /* Read Taylor series (divided differences) from file */
    read_T(ntori-1,ddOmega_FILE,ddOmega);

	double dphi = 2*M_PI/(NPOINTS-1);
	for(int i=0; i<NPOINTS; i++)
	{
		phi = i*dphi;

		/* Compute the SM: (I, phi) -> (Ip, phip) */
		SM(nfour, ntori, ddA, ddB, ddOmega, N, M, I, phi, &Ip, &phip);

		printf("%f %f\n", phip, Ip);
	}
    return 0;
}
